### ISSUE TITLE
为啥不向官方提个pr呢

### ISSUE THREAD

**Issue by tangxiangmin** [xueenze/flutter_webview_with_file_upload#1]
从这篇文章来的 https://blog.csdn.net/kameleon2013/article/details/109104531

感谢作者提出的解决方案。

请问一下这个为啥不向官方提一个PR呢? 这种修改插件源码的方式，如何保证后续插件版本的更新呢？

**Comment by xueenze** [comment]
> 从这篇文章来的 https://blog.csdn.net/kameleon2013/article/details/109104531
> 
> 感谢作者提出的解决方案。
> 
> 请问一下这个为啥不向官方提一个PR呢? 这种修改插件源码的方式，如何保证后续插件版本的更新呢？

我好像提了，目前我在webview 2.0.0的版本中做了同样的改造，还没有更新到这个仓库里，目前我的产品也稳定在2.0.0了，没有升级过了，也希望官方尽快做这个补充

**Comment by tangxiangmin** [comment]
哦哦好的，感谢你的回答
